std_msgs/Header header
uint16 name1 # MotorName
float32 pos1   # rad
float32 speed1   # rad
float32 current1

uint16 name2 # MotorName
float32 pos2   # rad
float32 speed2   # rad
float32 current2

uint16 name3 # MotorName
float32 pos3   # rad
float32 speed3   # rad
float32 current3

uint16 name4 # MotorName
float32 pos4   # rad
float32 speed4   # rad
float32 current4

uint16 name5 # MotorName
float32 pos5   # rad
float32 speed5   # rad
float32 current5

uint16 name6 # MotorName
float32 pos6   # rad
float32 speed6   # rad
float32 current6

uint16 name7 # MotorName
float32 pos7   # rad
float32 speed7   # rad
float32 current7

uint16 name8 # MotorName
float32 pos8   # rad
float32 speed8   # rad
float32 current8

uint16 name9 # MotorName
float32 pos9   # rad
float32 speed9   # rad
float32 current9

uint16 name10 # MotorName
float32 pos10   # rad
float32 speed10   # rad
float32 current10

uint16 name11 # MotorName
float32 pos11   # rad
float32 speed11   # rad
float32 current11

uint16 name12 # MotorName
float32 pos12   # rad
float32 speed12   # rad
float32 current12



